---
twitch_irc_server: "irc.chat.twitch.tv"
twitch_irc_port: 6697
twitch_channel_url: "https://www.twitch.tv/road_warrior99"
twitch_irc_channel: "#road_warrior99"
twitch_bot_response_prefix: "Raphael_bot: "
aws_region_id: "us-east-1"
aws_secret_id: "raphael-bot"
aws_language_code: "en-US"
ai_setup_prompt_file: "raphael-prompt.txt"
ai_model: "gpt-3.5-turbo"
obs_studio_host: "localhost"
obs_studio_port: "4455"
command_bot_name: "Rafael" #"Raphael" AWS can't spell
command_keywords:
  - Block
  - Mute
  - Kick
  - Scene
obs_scene_keywords:
  "Everything": "Seen full screen."
  "Development and Browser": "Scene split screen"
  "Pycharm": "Scene development"
  "BRB": "Scene be right back."
